### ISSUE TITLE
Training for parent discriminator

### ISSUE THREAD

**Issue by MikeXuQ** [kkanshul/finegan#11]
Hi, thanks for publishing your code. But after I reading the code, it makes me confused that the parent discriminator seems not to be updated anymore after initialized. It seems to be different from the paper. Have I ever missed anything important?
Looking forward to your answer, thanks!

**Comment by kidach1** [comment]
hi, parent discriminator seems to be updated at [line 335 of train.py](https://github.com/kkanshul/finegan/blob/master/code/trainer.py#L335) through information loss backward.
(and as written in the paper, adversarial loss isn't used in the parent stage.)

**Comment by utkarshojha** [comment]
Hi MikeXuQ,

The parent discriminator doesn't get trained as a usual discriminator. Instead, it gets optimized for the mutual information loss at the parent stage, along with the generator weights.

**Comment by MikeXuQ** [comment]
> Hi MikeXuQ,
> 
> The parent discriminator doesn't get trained as a usual discriminator. Instead, it gets optimized for the mutual information loss at the parent stage, along with the generator weights.

Thanks a lot!
