### ISSUE TITLE
FID-calculate-method

### ISSUE THREAD

**Issue by bravotty** [kkanshul/finegan#12]
Thank you for sharing.
I have a question about how to calculate the fid score between 'birds' dataset. Did u use the fine-tuned inceoption network to calculate the fid score or use other official fid calculate function ?

**Comment by bravotty** [comment]
And when i use released code/cfg/train.yaml. In Epoch 400, i test the FID value via https://github.com/bioinf-jku/TTUR this code, and which result FID value is up to 32. But in your released 'netG_birds.pth', i found that the FID value via https://github.com/bioinf-jku/TTUR is 18.79. 
Can u help me to solve this problem~? : )

**Comment by utkarshojha** [comment]
Hi,
FID is calculated using the Inception network pretrained on ImageNet (and no fine-tuning on the birds dataset). We had used a pytorch implementation of FID to calculate the score, not the one you have linked. 
And also, you need to perform hard negative training (described in section 7.2 of the supplementary), which happens after the 600 epochs in the code provided. Empirically, hard negative training helps in getting rid of some of the distorted fake images, and hence helps improving the realism (measured by FID).

Thanks

**Comment by bravotty** [comment]
Thanks!
