### ISSUE TITLE
The update of parameters in G

### ISSUE THREAD

**Issue by zzz313** [kkanshul/finegan#14]
Hi, I found that you do this after every time you call train_Gnet function. 
```
 for p, avg_p in zip(self.netG.parameters(), avg_param_G):
     avg_p.mul_(0.999).add_(0.001, p.data)
```
`avg_param_G` is the final parameters of your saved model. It looks like you update your model again after opt.step(). Why don't you save the final model directly but use this `avg_param_G`? 

Could you explain this to me? Thank you!

**Comment by utkarshojha** [comment]
Hi, saving the average model (where the newly updated weights of G only partially affect the overall parameters) results in a more stable model sometimes, which is not susceptible to unnatural updates in a particular iteration. 
This is a trick which some people have found to make the generator training more stable (e.g. StackGAN).

**Comment by zzz313** [comment]
Thanks！
