### ISSUE TITLE
About the data and pretrain models

### ISSUE THREAD

**Issue by abcdvzz** [kkanshul/finegan#2]
Could u pls upload the formatted CUB data and pretrained models to the Baidu Cloud(https://pan.baidu.com)? It's very hard for us to download large files in China. Sorry for that, it's just unstable to download something from Google driver. I don't know if it's convenient for u to enter this website (https://pan.baidu.com). If possible, pls upload it for us. Thank u very much.

**Comment by utkarshojha** [comment]
Hi, sorry for late reply. Here is the link for the formatted data (https://pan.baidu.com/s/10QtRgj7Y4gObpw8CtnPgpg); and the link for pre trained models (https://pan.baidu.com/s/1_m1qVpYdTky_WLTPXYGYsg).
