### ISSUE TITLE
About fine-tuned InceptionV3 .pth file

### ISSUE THREAD

**Issue by bravotty** [kkanshul/finegan#6]
Hi, what a wonderfull work!!!
When i was eval the network picture, IS value is up to 4.* without fine-tuned inception net in respective datasets.
Could u release the fine-tuned inceptionV3 network pth file on respective dataset(birds, cars, dogs)?
thx!!!

**Comment by utkarshojha** [comment]
Hi! Please fine the fine tuned models here.
https://drive.google.com/open?id=1ktzN4Tmb2LwoO0sx4SgH7XwILxw4T1wk
