### ISSUE TITLE
About test image generation

### ISSUE THREAD

**Issue by bravotty** [kkanshul/finegan#8]
Im confused about your paper word 'We evaluate image generation using Inception Score (IS) [42] and Frechet Inception Distance (FID) [20], which are computed on 30K randomly generated images (equal number of images for each child code c)' 
How can i generate 30k test image on CUB200 dataset? : )
Because in CUB200, parent class is 20, child class is 200, background class is 200.So that the final image is about 20x200x200= 800K. How can i get the 30K test image?

Also, how calc the FID value of CUB200 dataset? (e.g how to get the CUB200 mu and sigma?)

Hope for your reply~~~

**Comment by utkarshojha** [comment]
We generate equal number of images (150) for each child class (200 total). So the total number of generated images are 200*150 = 30k. While generating the fake images, we maintain the constraints as mentioned in the Section 3.1 in the main paper (tying of the latent child codes with (i) the parent code; (ii) the background code).

For calculating the FID, we use the pretrained inception network on the Imagenet dataset (not the fine-tuned one). Refer to this repository for more details (https://github.com/mseitzer/pytorch-fid)

**Comment by bravotty** [comment]
Thanks！
The images in CUB200 dataset are randomly sized. 
e.g. (228, 128, 3), (127, 340, 3)......
How can i get the same size input for calculating the FID? 
Resize (299, 299, 3) totally? or? 
Hope for your reply!

**Comment by utkarshojha** [comment]
FID scores can be evaluated on any image size (64x64, 128x128 etc.); what you need to ensure is that both the real and fake images are resized to the same resolution. Ultimately, all of the images before being fed to the inception network are resized to 299x299.

**Comment by bravotty** [comment]
Thanks!
